apiVersion: v1
kind: Service
metadata:
    name: "demo"
    labels:
        app: "demo"
spec:
    type: LoadBalancer
    ports:
    - port: 3478
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "demo"